apiVersion: v1
kind: Pod
metadata:
  name: cm-pod 
spec:
  containers:
  - name: resume-image
    image: roberttemta/resume-img:v3.0.10
    ports: 
    - containerPort: 80
    env: 
    - name: team
      valueFrom: 
        configMapKeyRef: 
          name: myconfigmap
          key: team
