apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod1 
spec:
  containers:
  - name: resume-image
    image: roberttemta/resume-img:v3.0.10
    ports: 
    - containerPort: 80
    env: 
    - name: SECRET_USERNAME
      valueFrom: 
        secretKeyRef:
          key: db_username 
          name: mysecret
    - name: SECRET_PASSWORD
      valueFrom: 
        secretKeyRef:
          key: db_password 
          name: mysecret
          
