apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - name: wordpress
    protocol: TCP
    port: 80
    targetPort: 80